routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

Route::namespace('User')->group(function () {
    Route::get('', 'HomeController@index');
    Route::get('category', 'CategoryController@index')->name('category');
    Route::get('sub_category/{id}', 'CategoryController@subCategory')->name('subCategory');
    Route::get('product', 'ProductController@index');
    Route::get('product/{id}', 'ProductController@detail');
    Route::get('category/{id}', 'CategoryController@detail')->name('categoryDetail');


});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public function getProductImagesAttribute()
    {
        return json_decode($this->images);
    }
}

resources/views/category.blade.php
@extends('master')
@section('content')
    <main id="content" class="globale-content content-page">
        <div class="container">
            <div class="brecump">
                <a href="home.html">Home</a> <img src="assets/images/arrow-right.png" alt="">
                <span>Categories</span>
            </div>
            <div class="categories">
                <h2 class="section-title">Categories</h2>
                <ul>
                    @foreach($categoryParents as $parent)
                        <li>
                            <a href="" class="cat-item image-fit">
                                <img src="{{ asset('storage/'.$parent->img) }}" alt="">
                                <h3>{{ $parent->name }}</h3>
                            </a>
                        </li>
                    @endforeach
                </ul>
            </div>
        </div>
    </main>
@stop

resources/views/home.blade.php
@extends('master')
@section('content')
    <div class="detail-slider">
        <div class="slider-item">
            <img src="assets/images/detail1.jpg" alt="">
        </div>
        <div class="slider-item">
            <img src="assets/images/detail2.jpg" alt="">
        </div>
        <div class="slider-item">
            <img src="assets/images/detail1.jpg" alt="">
        </div>
        <div class="slider-item">
            <img src="assets/images/detail1.jpg" alt="">
        </div>
        <div class="slider-item">
            <img src="assets/images/detail1.jpg" alt="">
        </div>
    </div>
    <main id="content" class="globale-content">
        <div class="container">
            <h1 class="section-title">Signature Salt Bath Treatment</h1>
            <div class="content-text">
                <p>Enjoy the full benefits of Sundara’s signature products which draw ingredients indigenous to the area. This treatment begins with exfoliation of the skin, followed by a luxurious bath soak and then full body hydration to conclude the service.</p>
            </div>
        </div>
    </main>
     <div class="suggestions">
	<div class="container">
		<h2 class="font-bold">Suggestion</h2>
		<div class="suggestions-slider">
			<ul>
                @foreach($products as $product)
				<li>
					<div class="sugges-item">
						<div class="image-fit"><img src="{{ asset('storage/'.$product->product_images[0]) }}" alt="{{$product->images}}"></div>
						<div class="info relative-section">
							<h3>{{$product->name}}</h3>
							<div class="des">{{$product->description}}</div>
							<div class="price">${{$product->price}}</div>
							<a href="" class="add-sugges">Add Suggesstion</a>
						</div>
					</div>
				</li>
                 @endforeach
			</ul>
		</div>
	</div>
</div>
{{--    <div id="addCarts">--}}
{{--        <div class="container">--}}
{{--            <div class="row">--}}
{{--                <div class="col-5">--}}
{{--                    <div class="total-price">--}}
{{--                        Total Price <b>$285.0</b>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--                <div class="col-7">--}}
{{--                    <div class="quatity text-right">--}}
{{--                        Qty:--}}
{{--                        <div class="number-custom relative-section">--}}
{{--                            <a href="" class="minus"></a>--}}
{{--                            <input type="number" name="" id="" value="1"  min="1">--}}
{{--                            <a href="" class="plus"></a>--}}
{{--                        </div>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--            <button class="btn btn-default font-bold">Add to Cart</button>--}}
{{--        </div>--}}
{{--    </div>--}}
@stop

resources/views/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>Item</title>
    <link rel="stylesheet" href="{{ asset('assets/fonts/font-awesome.css') }}">
    <link rel="stylesheet" href="{{ asset('bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/js/slick/slick.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/js/slick/slick-theme.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/main.css') }}">
    <link rel="shortcut icon" type="image/x-icon" href="assets/images/favicon.png" />
</head>
<body>
<div class="the-header">
    <header id="header">
        <div class="container">
            <div class="relative-section text-center">
                <a href="" class="toggle-menu"><img src="assets/images/menu.png" alt=""></a>
                <a href="home.html" class="logo"><img src="assets/images/logo.png" alt=""></a>
                <div class="header-right">

                    <a href="" class="toggle-cars relative-section"><img src="assets/images/cart-icon.png" alt=""><span>3</span></a>
                </div>
            </div>
        </div>
    </header>
</div>
<div class="menu-transform"></div>
<div id="menu-main">
    <div class="menu-inner">
        <a href="" class="menu-close"><img src="assets/images/menu-close.png" alt=""></a>
        <div class="languages text-left">
            <a href="" class="current"><img src="assets/images/fr.png" alt=""> Francais</a>
            <ul>
                <li><a href=""><img src="assets/images/fr.png" alt=""> Francais</a></li>
                <li><a href=""><img src="assets/images/en.jpg" alt=""> England</a></li>
            </ul>
        </div>
        <ul class="menu-main">
            <li><a href="home.html">Home</a></li>
            <li class="has-sub">
                <a href="">Categories</a>
                <ul class="sub-menu">
                    @foreach($categories as $category)
                        <li><a href="{{route('subCategory',$category->id)}}">{{ $category->name }}</a></li>
                    @endforeach
                </ul>
            </li>
        </ul>
        <a href="" class="logout-link">Log Out</a>
    </div>
</div>
@yield('content')


<footer id="footer" class="text-center">
    <div class="container">
        <div class="copyright">© 2020 Thalassa Concept. All rights reserved.</div>
    </div>
</footer>
<script src="{{ asset('assets/js/jquery-3.5.0.min.js') }}"></script>
<script src="{{ asset('bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/js/slick/slick.min.js') }}"></script>
<script src="{{ asset('assets/js/jquery.validate.min.js') }}"></script>
<script src="{{ asset('assets/js/main.js') }}"></script>
<script>
    jQuery(function($){
        $("#loginForm").validate({
            rules: {
                profile_id: "required",
                user_id: "required"
            },
            messages: {
                profile_id: "Please enter correct your profile id",
                user_id: "Please enter correct your user id"
            }
        });
        $('.detail-slider').slick({
            dots: true,
            infinite: true,
            autoplay: true,
            autoplaySpeed: 5000,
        });
        $('.suggestions ul').slick({
            infinite: true,
        });
        $('.nom-item li a').on('click',function() {
            $(this).toggleClass('active');
            return false;
        });
    })
</script>
</body>
</html>

resources/views/sub_category.blade.php
@extends('master')
@section('content')
    <main id="content" class="globale-content content-page">
        <div class="container">
            <div class="brecump">
                <a href="home.html">Home</a> <img src="assets/images/arrow-right.png" alt="">
                <a href="categories.html">Categories</a> <img src="assets/images/arrow-right.png" alt="">
                <span>{{ $category->name }}</span>
            </div>
            <h2 class="section-title">{{ $category->name }}</h2>
            <ul class="list-inline catsub-list text-center">
                @foreach($subCategories  as $category)
                <li class="item-inline">
                    <a class="catsub-item font-bold" href="">
                        <div class="image">
                            <img src="{{ asset('storage/'.$category->img) }}" alt="">
                        </div>
                        {{$category->name}}
                    </a>
                </li>
                @endforeach
            </ul>
        </div>
    </main>
@stop